### ISSUE TITLE
./gradlew stage doesnt work unless pushing to heroku HEAD:master

### ISSUE THREAD

**Issue by jaytheking** [heroku/heroku-buildpack-gradle#36]
Ive been working on a multi project gradle application, i was ready to test it out on heroku and follow all instructions on documentation for heroku gradle applications.

Because i already had the repo i just add the remote branch to my repo and tried pushing but resulted in this:
```
remote: -----> Using set buildpack heroku/gradle
remote: -----> Gradle app detected
remote: -----> Installing OpenJDK 1.8... done
remote: -----> Installing Gradle Wrapper...
remote:        WARNING: Your application does not have it's own gradlew file.
remote:        We'll install one for you, but this is a deprecated feature and
remote:        in the future may not be supported.
remote: -----> Building Gradle app...
remote:        WARNING: The Gradle buildpack is currently in Beta.
remote: -----> executing ./gradlew stage
remote:        :api:compileJavaNote: Some input files use unchecked or unsafe operations.
remote:        Note: Recompile with -Xlint:unchecked for details.
remote:        
```
Even though all the files that need to exist for gradle to work are commited and tracked, however when i push to HEAD:master then the gradle wrapper is detected and starts my build and succeeds.

**Comment by jkutner** [comment]
@jaytheking what buildpack URL are you using? The warning about Beta is old, and shouldn't be there. What is the output of `heroku buildpacks` command?

If `git push heroku HEAD:master` works, and `git push heroku master` does not, then it probably means you are working on a branch other than master. Run `git branch` to find out, and show me.

**Comment by jaytheking** [comment]
@jkutner Hey sorry, so because i couldnt get that message anymore when i figured i could push to HEAD:master to get it to work i had to find an older message with the same warning. Mine was the same except for the part about being in beta.

```
jacques@Flatbread:~$ heroku buildpacks -a linesmarts-dev
=== linesmarts-dev Buildpack URL
heroku/gradle
jacques@Flatbread:~$ 
```

```
jacques@Flatbread:~/Documents/GitHub/linesmarts (heroku_deployment-25-08-17)$ git branch
  client_api_integration_tests
* heroku_deployment-25-08-17
  master
jacques@Flatbread:~/Documents/GitHub/linesmarts (heroku_deployment-25-08-17)$
```
so yeah i am working on a branch because i didnt want the changes that i was making to break anything in the working build as i wasnt sure to begin with how much would need to change.

**Comment by jkutner** [comment]
@jaytheking if you're working on a branch you need to run `git push heroku HEAD:master` or `git push heroku heroku_deployment-25-08-17:master`.
