### ISSUE TITLE
Cache project-level cache between builds

### ISSUE THREAD

**Issue by docent** [heroku/heroku-buildpack-gradle#42]
Project level cache (stored, by default in root project's `.gradle` directory) is not cached between the builds. Because of that, projects need to be always fully rebuilt irrespective if there were changes or not. Gradle has a switch (`--project-cache-dir`) that can be used to set this directory.

**Comment by jkutner** [comment]
@docent can you test my branch by running:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-gradle#cache-gradle-project
```

Because the `--project-cache-dir` can't be set as an env var, I'd like to try creating the `.gradle` directory as a symlink to the cache. If this gives me trouble, I'll use the `--project-cache-dir` option as a last resort (it complicates how we define the default task and options).

**Comment by docent** [comment]
@jkutner thanks for making the changes. As I can tell, caching project-level `.gradle` looks OK. I'm wondering though, is it OK to use the same directory as for user-level `.gradle` cache which is already there in cache. Probably no problem with that, but thinking prospectively we might consider if this directory structure is OK.

Second thing is, in order to achieve incremental builds we would also need to also:
1. Cache the Gradle `build` directory - I already have some thoughts about it, so maybe we could create a separate issue? (unfortunately, this might be a bit more complex)
2. Allow caching of arbitrary directories like the dreaded `node_modules` directory that cannot be simply moved out of the source tree to the build directory. I see there is issue #19 and a corresponding branch, but I don't like the approach there in that it involves copying, and assumes some default locations to be cached, which cover only some specific use cases (e.g. in my case, I don't use bower and my `node_modules` directory is in a subproject. I would rather see a more general approach that doesn't even name `node_modules` specifically (as we are in Gradle after all) and instead allows to cache arbitrary directories using (maybe) the symlink approach by kind of mirroring their relative location in the project in the cache directory (or rather subdirectory).

Let me know your thoughts

**Comment by jkutner** [comment]
@docent thanks for your feedback! I'm not 100% confident the project cache and user cache can be combined (and it might be good to have them separate in the future). So I've changed my PR to use different dirs for each.

Can you create a new issue for the caching of `build` directory? If you can describe what needs to be cached, I'm sure I can make it happen (we do a similar thing with sbt and the Scala buildpack).

Do you have any recommendations for how you might configure custom cache directories? I'm happy to try that.

**Comment by jkutner** [comment]
I've merged my PR into master, so you can now use it with:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-gradle
```
