### ISSUE TITLE
Spring Boot detection fails for several cases

### ISSUE THREAD

**Issue by fmakdemir** [heroku/heroku-buildpack-gradle#52]
Spring Boot detection code at [here](https://github.com/heroku/heroku-buildpack-gradle/blob/master/lib/common.sh#L23) fails to detect several cases:
* using the verbose format of compile group: `'org.springframework.boot', name: 'spring-boot-starter-test'`
* having a multi module structure and using boot dependencies only in submodules instead of root module
* not having dependencies in root and using plugins block to include spring boot plugin

Possible solution: changing regex to `"^[^/].*org.springframework.boot"`. Removing `:spring-boot` handles these problems unless there was a specific reason for that part to be present. In that case above cases could be handled separately.

**Comment by jkutner** [comment]
@fmakdemir i think that's a reasonable solution, although I might want to keep the `:` so that `org.springframework.boot` doesn't catch on something that's not really a dependency. Do you think that would work?

**Comment by fmakdemir** [comment]
In that case I think at least including both short and long format for it would be nice or instead of detecting the dependencies it can detect plugins with `spring-boot-gradle-plugin|(id.*org.springframework.boot)`
