### ISSUE TITLE
Heroku CI slow builds

### ISSUE THREAD

**Issue by anderssv** [heroku/heroku-buildpack-gradle#54]
Hi,

I've been having a dialogue with Heroku Support about the speed of the build in the Heroku CI tests. In general there's not much they can do there they say. So I'm asking here even though I realize it's kind of a long shot. Hoping there might be some Gradle specifics that can make it faster. :)

I notice it takes about 2:30 before anything starts happening in the build output "-----> Auto detecting buildpacks...". I also see it downloads Gradle (through gradlew) on every run. Is it the Git repo that drives the time to start? Is Gradle using more disk activity than others when building, that makes it slower?

Is there something we can do on our side to optimize the run-time? Our tests are (relatively) fast, so it's about 20% of the run-time. Even parallelizing the build on Heroku doesn't yield any extra performance because it's the surrounding stuff that takes time.

Thanks,
Anders,

**Comment by jamesward** [comment]
On other environments I've also seen Gradle seem to just do nothing for a while.  I think it helped to turn off the Gradle Daemon and set `--console=plain` (or maybe that just revealed what it was doing).  Also I don't think the buildpack currently caches the downloaded Gradle version, which would save some time too.

**Comment by anderssv** [comment]
According to support, caching is not available in the Heroku CI. I think it's a bit on the side of what you can do within the regular builds, but it's hard to understand all the details. 

How do I set any options to the Gradle command for CI? As it has two stages I think it doesn't use the default GRADLE_TASK? I just use the autodetected runner from the buildpack. :)

**Comment by jkutner** [comment]
Here are [some docs on configuring Gradle apps](https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku). There is a `GRADLE_TASK` env var. The buildpack already adds ` --no-daemon` but maybe there are other options that will speed this up.

**Comment by anderssv** [comment]
Thanks for the input guys. It seems there are about 2-3 minutes of housekeeping on the Heroku side, and then about 5-7 minutes running tests and compiling. Not much to do about that now, but will try to run on other CIs to see what timings we can achive there. Even though it's not directly comparable, we are running builds locally in about 2 minutes (remote DB). So might get i running a little bit faster. :)

**Comment by anderssv** [comment]
Just for reference: Running the same build (on free plan) on CircleCI in about 3:20 .

**Comment by Malax** [comment]
This was probably caused by https://github.com/heroku/heroku-buildpack-gradle/pull/82
